### ISSUE TITLE
TypeError: Cannot read property 'owner_id' of undefined at Proxy.owner_id

### ISSUE THREAD

**Issue by byrnereese** [ringcentral-tutorials/ringcentral-ai-bot#62]
This is returned by the server when I click "Add to Glip" for the first time. 

I followed the directions as specified except I did NOT specify a value for `GOOGLE_APPLICATION_CREDENTIALS` in my `.env` file. I am not sure if that would have resulted in this error however. 

In looking at the `ringcentral_concise` npm in `ringcentral.js` I see that when setting the token for the client, the token is stored as a scalar. There is no `owner_id` parameter that I can see.

**Comment by byrnereese** [comment]
Here is a trace from the server which contains more info

```
2018-11-06T18:49:32.384Z ringcentral-ai-bot server start on --> http://localhost:7867
  <-- POST /bot-oauth
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) ----------event get--------------
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) { headers:
   { 'content-length': '461',
     'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
     host: 'dd195736.ngrok.io',
     'user-agent': 'Apache-HttpClient/4.5.2 (Java/1.8.0_172)',
     'accept-encoding': 'gzip,deflate',
     'x-forwarded-proto': 'https',
     'x-forwarded-for': '199.68.212.132' },
  queryStringParameters: {},
  body:
   { access_token:
      'U0pDMTFQMDFQQVMwMHxBQUJZUVVFVGMzeG90R05zTHNuaTRYd2JxbVd2c2U4RS1OMXF2ejI2Rk9tT2pra0xCMjBfcS1sU05HZVp6RWJYYTR4NF9QWWRPMEVYNENYQjd4dmJsWHJoMm1yR3hjRnJkT1k4RWFEc3FFZ0lVQjljQ3lveWJTY2tNOU9pRjY3ZmhlZkpBS1EyclBSSmNsTHRiX18yYTdUa1ZlNGJXLU15a3RraEpCMDRVeHpBY3FaVVktV05jN0NqYzBVSG5UeER2cE95dGhDdy1GOEFuREwzendrcGZRYXF8Njl5RmNnfGJvWFZjZ1BpSzhMeGQ3Und2TXRXQkF8QUE',
     creator_extension_id: '62625926007',
     creator_account_id: '62625926007',
     client_id: 'pt_XbD8lRMiF9EgyoYV5hA' },
  path: '/bot-oauth',
  pathParameters: { action: 'bot-oauth' } }
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) -----------event get-------------
2018-11-06T18:54:03.351Z Bot authorize error { error: 'invalid_request',
  error_description: 'Resource Owner credentials are incomplete',
  errors:
   [ { errorCode: 'OAU-143',
       message: 'Resource Owner credentials are incomplete' } ] }
2018-11-06T18:54:03.367Z server error TypeError: Cannot read property 'owner_id' of undefined
    at Proxy.owner_id (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/src/lamda/lib/store.js:87:20)
  --> POST /bot-oauth 500 124ms 237b
```

**Comment by byrnereese** [comment]
Here is a trace from the server which contains more info:

```
2018-11-06T18:49:32.384Z ringcentral-ai-bot server start on --> http://localhost:7867
  <-- POST /bot-oauth
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) ----------event get--------------
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) { headers:
   { 'content-length': '461',
     'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
     host: 'dd195736.ngrok.io',
     'user-agent': 'Apache-HttpClient/4.5.2 (Java/1.8.0_172)',
     'accept-encoding': 'gzip,deflate',
     'x-forwarded-proto': 'https',
     'x-forwarded-for': '199.68.212.132' },
  queryStringParameters: {},
  body:
   { access_token:
      'U0pDMTFQMDFxxxxxxxxxxxxxxxXQkF8QUE',
     creator_extension_id: '62625926007',
     creator_account_id: '62625926007',
     client_id: 'pt_XbD8lxxxxxxxxEgyoYV5hA' },
  path: '/bot-oauth',
  pathParameters: { action: 'bot-oauth' } }
Tue Nov 06 2018 10:54:03 GMT-0800 (Pacific Standard Time) -----------event get-------------
2018-11-06T18:54:03.351Z Bot authorize error { error: 'invalid_request',
  error_description: 'Resource Owner credentials are incomplete',
  errors:
   [ { errorCode: 'OAU-143',
       message: 'Resource Owner credentials are incomplete' } ] }
2018-11-06T18:54:03.367Z server error TypeError: Cannot read property 'owner_id' of undefined
    at Proxy.owner_id (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/src/lamda/lib/store.js:87:20)
  --> POST /bot-oauth 500 124ms 237b
```

**Comment by zxdong262** [comment]
Could not reproduce, Guessing maybe your client key or secret not right, try check that. I changed my key or secret to false one, would get `'owner_id' of undefined` error too, and a `OAU-153` error.

**Comment by byrnereese** [comment]
Upon further inspection, the problem was stemming from the fact that I misconfigured the RC App to be a private bot. During OAuth, RC POSTs an `access_token` directly to the bot/server which results in a failure to find the temporary token. A public bot goes through all three legs of the OAuth handshake and succeeds.
