### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Invalid text content: too few tokens (words) to process

### ISSUE THREAD

**Issue by byrnereese** [ringcentral-tutorials/ringcentral-ai-bot#72]
In my first successful transcription, now that Google has been setup properly, I did get a transcribed message in Glip. However, I noticed in my server console the following error was thrown:

```
2018-11-07T21:41:43.139Z classifies ERROR: { Error: 3 INVALID_ARGUMENT: Invalid text content: too few tokens (words) to process.
    at Object.exports.createStatusError (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:841:24)
```

## Full Console Log

```
Wed Nov 07 2018 13:41:40 GMT-0800 (Pacific Standard Time) -----------event get-------------
Wed Nov 07 2018 13:41:40 GMT-0800 (Pacific Standard Time) db user get { id: '248664004' }

Wed Nov 07 2018 13:41:40 GMT-0800 (Pacific Standard Time) db cache get { id: '13e9061dff11e0e166d7f9a4b7955f24' }
Wed Nov 07 2018 13:41:40 GMT-0800 (Pacific Standard Time) url to text : https://media.devtest.ringcentral.com/restapi/v1.0/account/248664004/extension/248664004/message-store/5468530004/content/5468530004 { Authorization:
   'Bearer U0pxxxxQUE' }

2018-11-07T21:41:42.767Z https://media.devtest.ringcentral.com/restapi/v1.0/account/248664004/extension/248664004/message-store/5468530004/content/5468530004 Transcription:  this is another test voicemail
Wed Nov 07 2018 13:41:42 GMT-0800 (Pacific Standard Time) url to text result: this is another test voicemail
2018-11-07T21:41:43.139Z classifies ERROR: { Error: 3 INVALID_ARGUMENT: Invalid text content: too few tokens (words) to process.
    at Object.exports.createStatusError (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/byrne.reese/Projects/ringcentral/ringcentral-ai-bot/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 3,
  metadata:
   Metadata {
     _internal_repr:
      { 'google.rpc.badrequest-bin': [Array],
        'grpc-status-details-bin': [Array] } },
  details: 'Invalid text content: too few tokens (words) to process.',
  note:
   'Exception occurred in retry method that was not classified as transient' }
Wed Nov 07 2018 13:41:43 GMT-0800 (Pacific Standard Time) analysis text result: { text: 'this is another test voicemail',
  sentiment:
   { magnitude: 0.10000000149011612, score: -0.10000000149011612 },
  syntax:
   { sentences: [ [Object] ],
     tokens: [ [Object], [Object], [Object], [Object], [Object] ],
     language: 'en' },
  entitySentiments:
   [ { mentions: [Array],
       metadata: {},
       name: 'test voicemail',
       type: 'OTHER',
       salience: 1,
       sentiment: [Object] } ],
  classification: undefined }
Wed Nov 07 2018 13:41:43 GMT-0800 (Pacific Standard Time) db cache add { id: '13e9061dff11e0e166d7f9a4b7955f24',
  result:
   { text: 'this is another test voicemail',
     sentiment:
      { magnitude: 0.10000000149011612, score: -0.10000000149011612 },
     syntax: { sentences: [Array], tokens: [Array], language: 'en' },
     entitySentiments: [ [Object] ],
     classification: undefined } }
Wed Nov 07 2018 13:41:43 GMT-0800 (Pacific Standard Time) db bot get { id: '251102004' }
  --> POST /user-webhook 200 4,358ms 11b
  <-- POST /bot-webhook
```

**Comment by zxdong262** [comment]
Just log google's feedback, not an error, voicemail too short.
